import Head from "next/head"
import Footer from "../footer"
import NavBar from "../navigation/NavBar"

const MainLayout = ({ children }) => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <main className="flex flex-col w-full pt-12">
                {children}
            </main>

            <footer >
                <Footer />
            </footer>
        </div>
    )
}

export default MainLayout